// Core session management

export { type Args, parseArgs } from "./cli/args.ts";

// Config paths
export {
	CONFIG_DIR_NAME,
	getAgentDir,
	getDocsPath,
	getExamplesPath,
	getPackageDir,
	getReadmePath,
	VERSION,
} from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
export {
	type AgentClarificationQuestion,
	type AgentClarificationRequest,
	type AgentControlSnapshot,
	type AgentControlStatus,
	type AgentControlToolDetails,
	type AgentLifecycleEvent,
	type AgentLifecycleEventListener,
	type AgentLifecycleEventType,
	AgentPool,
	type AgentPoolConfig,
	type AgentPoolDependencies,
	type AgentProfile,
	type AgentProgressEvent,
	type AgentTaskActivity,
	type AgentTaskActivityOutcome,
	type AgentTaskBudgetSummary,
	type AgentTaskCheck,
	type AgentTaskCitation,
	type AgentTaskError,
	type AgentTaskProgressListener,
	type AgentTaskResult,
	type AgentTaskStatus,
	type AgentTaskUsage,
	type AgentTerminalCapture,
	type AgentTerminalReference,
	AgentTerminalRuntime,
	type AgentTerminalRuntimeOptions,
	DEFAULT_AGENT_PROFILE,
	DEFAULT_AGENT_PROFILES,
	DEFAULT_IMPLEMENTER_PROFILE,
	DEFAULT_RESEARCHER_PROFILE,
	type DelegateTaskInput,
	validateAgentPoolConfig,
	validateAgentProfile,
} from "./core/agents/index.ts";
export { readStoredCredential } from "./core/auth-storage.ts";
export * from "./core/background/index.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	generateSummaryWithUsage,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
// Document Runtime and Execution Contract
export * from "./core/documents/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentSettledEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderHeadersEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	EntryRenderer,
	EntryRenderOptions,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InlineExtension,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageEndEvent,
	MessageRenderer,
	MessageRenderOptions,
	MessageStartEvent,
	MessageUpdateEvent,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionInfoChangedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionEndEvent,
	ToolExecutionMode,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export {
	type ModelScopeDiagnostic,
	type ResolveCliModelResult,
	type ResolveModelScopeResult,
	resolveCliModel,
	resolveModelScopeWithDiagnostics,
	type ScopedModel,
} from "./core/model-resolver.ts";
export {
	type CreateModelRuntimeOptions,
	ModelRuntime,
	type ModelRuntimeAuthOverrides,
} from "./core/model-runtime.ts";
export * from "./core/monitor/index.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
	StagedPackageSource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export * from "./core/playwright/index.ts";
export * from "./core/policy/index.ts";
export * from "./core/privilege/index.ts";
export * from "./core/remote/index.ts";
export type {
	DefaultResourceLoaderOptions,
	ResourceCollision,
	ResourceDiagnostic,
	ResourceLoader,
	ResourceLoaderReloadOptions,
	ResourceLoaderSkillProjection,
	SkillPolicyDiagnosticReason,
} from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";
export * from "./core/search/index.ts";
export {
	type BranchSummaryEntry,
	buildContextEntries,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type SessionTreeNode,
	sessionEntryToContextMessages,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type DefaultProjectTrust,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
} from "./core/settings-manager.ts";
// Skills
export {
	createSkillAllowlistOverride,
	formatSkillSource,
	formatSkillSourceDetails,
	getSkillRegistryScopePaths,
	loadSkillRegistry,
	resolveSkillRegistryProjection,
	SKILL_REGISTRY_FILENAME,
	SKILL_REGISTRY_VERSION,
	type SkillAllowlist,
	type SkillDiagnosticCode,
	type SkillDiagnosticSeverity,
	type SkillInventory,
	type SkillRegistryDiagnostic,
	type SkillRegistryEntry,
	type SkillRegistryFile,
	type SkillRegistryLoadResult,
	type SkillRegistryProjection,
	type SkillRegistryRecord,
	type SkillRegistryScope,
	type SkillRegistryScopePaths,
	type SkillRegistrySnapshot,
	type SkillResourceSet,
	type SkillSource,
	type SkillValidationResult,
	validateSkillRegistryEntry,
	writeSkillRegistry,
} from "./core/skill-registry.ts";
export { parseSkillRegistryCommand, type SkillRegistryCommand } from "./core/skill-registry-commands.ts";
export {
	parseRemoteSkillSource,
	type SkillFileReadResult,
	type SkillRegistryImportResult,
	type SkillRegistryMutationResult,
	type SkillRegistryRemoveResult,
	SkillRegistryService,
	SkillRegistryServiceError,
	type SkillRegistryServiceOptions,
	type SkillRemoteFetcher,
	type SkillRemoteFetchResult,
	type SkillSecurityReview,
	type SkillSecurityReviewConfirmation,
} from "./core/skill-registry-service.ts";
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
	validateSkillDescription,
	validateSkillName,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
export {
	attachTaskLedgerToolDetails,
	type CommandRecord,
	createCommandSignature,
	type FailureRecord,
	type FileModificationRecord,
	type FileReadRecord,
	getTaskLedgerToolDetails,
	isCommitCommand,
	isGitStatusCommand,
	isVerificationCommand,
	type NetworkToolRecord,
	selectTaskTodos,
	TASK_LEDGER_DETAILS_KEY,
	TASK_LEDGER_DETAILS_VERSION,
	TASK_LEDGER_DUPLICATE_WINDOW_MS,
	TASK_LEDGER_RECENT_COMPLETION_MS,
	type TaskCommandStatus,
	type TaskCompletionCriterionState,
	type TaskDocumentContractSnapshot,
	type TaskDocumentItemStatus,
	type TaskInteractionRecord,
	type TaskLedgerSnapshot,
	type TaskLedgerToolDetails,
	type TaskPhase,
	type TaskRequiredCheckState,
	type TaskRequirementState,
	type TaskTodo,
	type TaskTodoStatus,
	type TaskVerificationStatus,
	taskTodoSelectionRank,
	type VerificationState,
} from "./core/state/task-ledger.ts";
export { type EditDiffResult, generateDiffString, generateUnifiedPatch } from "./core/tools/edit-diff.ts";
// Tools
export {
	ASK_USER_QUESTION_PARAMETERS,
	ASK_USER_QUESTION_TOOL_NAME,
	type AskUserQuestionInput,
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	BashToolExecutionError,
	type BashToolInput,
	type BashToolOptions,
	createAskUserQuestionToolDefinition,
	createBashToolDefinition,
	createDocsReadToolDefinition,
	createDocsResolveTaskToolDefinition,
	createDocsSearchToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createPlaywrightToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type DocsReadInput,
	type DocsReadToolDetails,
	type DocsResolveTaskInput,
	type DocsResolveTaskToolDetails,
	type DocsSearchInput,
	type DocsSearchToolDetails,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type PendingQuestionInteraction,
	type PlaywrightInput,
	PlaywrightRuntime,
	type PlaywrightRuntimeOptions,
	type PlaywrightRuntimeToolDetailsV1,
	type PlaywrightSettings,
	type PlaywrightTarget,
	type PlaywrightToolDetails,
	QUESTION_ANSWER_SCHEMA,
	QUESTION_LIMITS,
	QUESTION_OPTION_SCHEMA,
	QUESTION_RESULT_SCHEMA,
	QUESTION_RESULT_VERSION,
	QUESTION_SCHEMA,
	type QuestionAnswer,
	type QuestionInteractionHandler,
	type QuestionInteractionRequest,
	type QuestionInteractionResponse,
	type QuestionOption,
	type QuestionResult,
	QuestionRuntime,
	type QuestionRuntimeOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type UserQuestion,
	validateQuestionAnswers,
	type WriteOperations,
	type WriteToolDetails,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
export * from "./core/workflow/index.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcQuestionHandler,
	type RpcQuestionRequest,
	type RpcResponse,
	type RpcSessionState,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BackgroundTaskComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	QuestionSelectorComponent,
	type QuestionSelectorOptions,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	type SkillRegistryAction,
	SkillRegistrySelectorComponent,
	type SkillRegistrySelectorOptions,
	selectTimelineCommands,
	TaskLedgerWidget,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	taskTodoLimit,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
	WorkflowSnapshotComponent,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeBg,
	type ThemeBgColors,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
