/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
} from "./agent-session-runtime.ts";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
} from "./agent-session-services.ts";
export {
	type AgentLifecycleEvent,
	type AgentLifecycleEventListener,
	type AgentLifecycleEventType,
	AgentPool,
	type AgentPoolConfig,
	type AgentPoolDependencies,
	type AgentProfile,
	type AgentProgressEvent,
	type AgentTaskBudgetSummary,
	type AgentTaskCheck,
	type AgentTaskCitation,
	type AgentTaskError,
	type AgentTaskProgressListener,
	type AgentTaskResult,
	type AgentTaskStatus,
	type AgentTaskUsage,
	DEFAULT_AGENT_PROFILE,
	DEFAULT_AGENT_PROFILES,
	DEFAULT_IMPLEMENTER_PROFILE,
	DEFAULT_RESEARCHER_PROFILE,
	type DelegateTaskInput,
	validateAgentPoolConfig,
	validateAgentProfile,
} from "./agents/index.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export type { CompactionResult } from "./compaction/index.ts";
export * from "./documents/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
export { areExperimentalFeaturesEnabled } from "./experimental.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentSettledEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type InlineExtension,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export * from "./monitor/index.ts";
export * from "./remote/index.ts";
export {
	DefaultResourceLoader,
	type DefaultResourceLoaderOptions,
	loadProjectContextFiles,
	type ResourceCollision,
	type ResourceDiagnostic,
	type ResourceLoader,
	type ResourceLoaderReloadOptions,
	type ResourceLoaderSkillProjection,
	type SkillPolicyDiagnosticReason,
} from "./resource-loader.ts";
export * from "./search/index.ts";
export {
	createSkillAllowlistOverride,
	formatSkillSource,
	formatSkillSourceDetails,
	getSkillRegistryScopePaths,
	loadSkillRegistry,
	resolveSkillRegistryProjection,
	SKILL_REGISTRY_FILENAME,
	SKILL_REGISTRY_VERSION,
	type SkillAllowlist,
	type SkillDiagnosticCode,
	type SkillDiagnosticSeverity,
	type SkillInventory,
	type SkillRegistryDiagnostic,
	type SkillRegistryEntry,
	type SkillRegistryFile,
	type SkillRegistryLoadResult,
	type SkillRegistryProjection,
	type SkillRegistryRecord,
	type SkillRegistryScope,
	type SkillRegistryScopePaths,
	type SkillRegistrySnapshot,
	type SkillResourceSet,
	type SkillSource,
	type SkillValidationResult,
	validateSkillRegistryEntry,
	writeSkillRegistry,
} from "./skill-registry.ts";
export { parseSkillRegistryCommand, type SkillRegistryCommand } from "./skill-registry-commands.ts";
export {
	parseRemoteSkillSource,
	type SkillFileReadResult,
	type SkillRegistryImportResult,
	type SkillRegistryMutationResult,
	type SkillRegistryRemoveResult,
	SkillRegistryService,
	SkillRegistryServiceError,
	type SkillRegistryServiceOptions,
	type SkillRemoteFetcher,
	type SkillRemoteFetchResult,
	type SkillSecurityReview,
	type SkillSecurityReviewConfirmation,
} from "./skill-registry-service.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
export {
	attachTaskLedgerToolDetails,
	type CommandRecord,
	createCommandSignature,
	type FailureRecord,
	type FileModificationRecord,
	type FileReadRecord,
	getTaskLedgerToolDetails,
	isCommitCommand,
	isGitStatusCommand,
	isVerificationCommand,
	type NetworkToolRecord,
	selectTaskTodos,
	TASK_LEDGER_DETAILS_KEY,
	TASK_LEDGER_DETAILS_VERSION,
	TASK_LEDGER_DUPLICATE_WINDOW_MS,
	TASK_LEDGER_RECENT_COMPLETION_MS,
	type TaskCommandStatus,
	type TaskCompletionCriterionState,
	type TaskDocumentContractSnapshot,
	type TaskDocumentItemStatus,
	TaskLedger,
	type TaskLedgerSnapshot,
	type TaskLedgerToolDetails,
	type TaskPhase,
	type TaskRequiredCheckState,
	type TaskRequirementState,
	type TaskTodo,
	type TaskTodoStatus,
	type TaskVerificationStatus,
	taskTodoSelectionRank,
	type VerificationState,
} from "./state/task-ledger.ts";
